#Persistent volume claim definition

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  resources:
    requests:
      storage: 10Gi
 
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeName: mongo-pv

