apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: custom-standard
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  zone: us-central1-a
  fstype: ext4
reclaimPolicy: Retain
volumeBindingMode: Immediate
